title: Sistema de riego automatico alimentado por energia solar
description: Este proyecto propone el diseño de un sistema de riego automatizado y alimentado con energía solar, consiste en utilizar un sensor de huemdad para regar una planta cada vez que sea necesario, este estara alimentado por un panel solar

repository: Sensors/sistema de riego automatico

plugins:
  - jekyll-redirect-from

exclude:
  - .git
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - collections
  - test
  - topics
  - vendor

collections:
  topics:
  explore_collections:
